### ISSUE TITLE
Error upon build

### ISSUE THREAD

**Issue by JRV77** [madgik/Docker-Exareme#2]
Hi,

My Exareme docker has been working fine so far but I had to re-build it today and got the following message:![image](https://cloud.githubusercontent.com/assets/15652034/19685270/067a6f08-9abc-11e6-999c-18eb3f7b97f9.png)
Could you look into it?
Thanks
Jean-Raphaël Vieille

**Comment by johnchronis** [comment]
Hello Jean,
we have corrected the issue. Try rebuilding the container with the no cache option 
(docker build --no-cache -t exareme .)

Yannis
